language: java

jdk:
  - oraclejdk8

before_script:
  - mongod --version
  - |-
    echo "replication:
      replSetName: rs0" | sudo tee -a /etc/mongod.conf
  - sudo service mongod restart
  - sleep 20
  - |-
    mongo --eval "rs.initiate({_id: 'rs0', members:[{_id: 0, host: '127.0.0.1:27017'}]});"
  - sleep 15

services:
  - mongodb

env:
  matrix:
    - PROFILE=ci
    - PROFILE=mongo36-next

# Current MongoDB version is 2.4.2 as of 2016-04, see https://github.com/travis-ci/travis-ci/issues/3694
# apt-get starts a MongoDB instance so it's not started using before_script
addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
    - oracle-java8-installer

sudo: false

cache:
  directories:
    - $HOME/.m2

install:
  - |-
    mongo admin --eval  "db.adminCommand({setFeatureCompatibilityVersion: '3.4'});"

script: "mvn clean dependency:list test -P${PROFILE} -Dsort"
